Task 2/days of week
yanakrupets/TMS.Net07.Homework pull request #2
Opened 2021-02-01 16:07 UTC by yanakrupets

2021-02-02 20:29 UTC, radzevich requested changes

2021-02-02 20:29 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/middle.cs
> +    class middle
```suggestion
    class Middle
```

In C# we usually name classes and methods from upper-case letter

2021-02-02 20:29 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/middle.cs
> +         public static void task()
```suggestion
         public static void Task()
```

2021-02-02 20:29 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/middle.cs
> +            DateTime date = new DateTime();
Creating a `DateTime` instance requires some resources. However, its value will be overwritten in the 30-st line. So, we can just declare a variable.
```suggestion
            DateTime date;
```

2021-02-02 20:29 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +                else if (partsOfDate[0].ToUpper() == "EXIT")
How about checking this condition in `while` instead of while `true`?

2021-02-02 20:29 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +        private int m_day;
```suggestion
        private int _day;
```
Oh, my lovely c++ :)
In C# we usually name private fields with an underscore

2021-02-02 20:29 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +            if (Check(day, month, year) == false)
Can be simplified
```suggestion
            if (!Check(day, month, year))
```

2021-02-02 20:29 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +            if (Check(m_day, m_month, m_year) == true)
Can be simplified
```suggestion
            if (Check(m_day, m_month, m_year))
```

2021-02-02 20:29 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +                    if (i == 100 || i == 200 || i == 300 || i == 500 || i == 600 || i == 700 || i == 900 || i == 1000 || i == 1100 || i == 1300 || i == 1400
We already know about `%` operator. It can help you to reduce the complexity of this statement

2021-02-02 20:29 UTC, radzevich commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +        public bool Check(int checkDay, int checkMonth, int checkYear)
Its a bit not clear what does this method checks. Please, make its name more valuable

2021-02-05 15:29 UTC, yanakrupets commented on TMS.Net07.Homework.DaysOfWeek/middle.cs
> +    class middle
done

2021-02-05 15:30 UTC, yanakrupets commented on TMS.Net07.Homework.DaysOfWeek/middle.cs
> +         public static void task()
done

2021-02-05 15:30 UTC, yanakrupets commented on TMS.Net07.Homework.DaysOfWeek/middle.cs
> +            DateTime date = new DateTime();
done

2021-02-05 15:30 UTC, yanakrupets commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +                else if (partsOfDate[0].ToUpper() == "EXIT")
done

2021-02-05 15:30 UTC, yanakrupets commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +        private int m_day;
done))

2021-02-05 15:30 UTC, yanakrupets commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +            if (Check(day, month, year) == false)
done

2021-02-05 15:31 UTC, yanakrupets commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +            if (Check(m_day, m_month, m_year) == true)
done

2021-02-05 15:31 UTC, yanakrupets commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +                    if (i == 100 || i == 200 || i == 300 || i == 500 || i == 600 || i == 700 || i == 900 || i == 1000 || i == 1100 || i == 1300 || i == 1400
done

2021-02-05 15:31 UTC, yanakrupets commented on TMS.Net07.Homework.DaysOfWeek/hard.cs
> +        public bool Check(int checkDay, int checkMonth, int checkYear)
done

2021-02-07 17:24 UTC, radzevich approved these changes
Feel free to merge

2021-02-07 20:54 UTC, merged