Task 3/calculator
yanakrupets/TMS.Net07.Homework pull request #3
Opened 2021-02-07 17:16 UTC by yanakrupets

2021-02-07 20:02 UTC, radzevich requested changes

2021-02-07 20:02 UTC, radzevich commented on TMS.Net07.Homework.Calculator/Middle.cs
> +                        Console.WriteLine($"Result is {number1 / number2}");
Need check, that `number` is not a `0`

2021-02-07 20:02 UTC, radzevich commented on TMS.Net07.Homework.Calculator/Easy.cs
> +                    decimal EURtoBYN = 3.16m;
```suggestion
                    const decimal EURtoBYN = 3.16m;
```
Compiler substitutes constant values into places, where they are used, instead of their names. That's why they don't require additional memory while an application running time. And that's why it's better to use them when values are not supposed to be changed

2021-02-07 20:02 UTC, radzevich commented on TMS.Net07.Homework.Calculator/Hard.cs
> +                else if (expression[0] == 's' && expression[1] == 'q' && expression[2] == 'r' && expression[3] == 't')
```suggestion
                else if (expression.StartsWith("sqrt"))
                {
                     operation = "sqrt";
                     i += operation.Length;
                                    
                     break;
                }
```

2021-02-07 20:02 UTC, radzevich commented on TMS.Net07.Homework.Calculator/Hard.cs
> +                string[] partsOfExpression = expression.Split(Convert.ToChar('t'));
```suggestion
                string[] partsOfExpression = expression.Split('t');
```
`'t'` is already `char`. Why should we convert char to char?

2021-02-07 20:02 UTC, radzevich commented on TMS.Net07.Homework.Calculator/Hard.cs
> +                    expression = expression.Replace("o", string.Empty);
can we just add `2` to `i` index, instead of changing the input expression

2021-02-07 20:02 UTC, radzevich commented on TMS.Net07.Homework.AdditionalTaskForHW3/Program.cs
> +                switch(choise.ToLower())
`ToLower` and `ToUpper` work only for letters: 
"a".ToLower() -> "A";
"hElloW World".ToLower() -> "hello world";
"hElloW World".ToUpper() -> "HELLO WORLD"

In our case, the expected input is either 1, 2, 3, or 4. That's why the `ToLower` call is redundant

2021-02-09 19:13 UTC, yanakrupets commented on TMS.Net07.Homework.Calculator/Middle.cs
> +                        Console.WriteLine($"Result is {number1 / number2}");
yes, silly mistake, corrected

2021-02-09 19:14 UTC, yanakrupets commented on TMS.Net07.Homework.Calculator/Easy.cs
> +                    decimal EURtoBYN = 3.16m;
done

2021-02-09 19:15 UTC, yanakrupets commented on TMS.Net07.Homework.Calculator/Hard.cs
> +                else if (expression[0] == 's' && expression[1] == 'q' && expression[2] == 'r' && expression[3] == 't')
done

2021-02-09 19:17 UTC, yanakrupets commented on TMS.Net07.Homework.Calculator/Hard.cs
> +                string[] partsOfExpression = expression.Split(Convert.ToChar('t'));
just forgot to fix what I wrote earlier, corrected

2021-02-09 19:21 UTC, yanakrupets commented on TMS.Net07.Homework.Calculator/Hard.cs
> +                    expression = expression.Replace("o", string.Empty);
we discussed it and I explained why I did this, so it`s not corrected

2021-02-09 19:22 UTC, yanakrupets commented on TMS.Net07.Homework.AdditionalTaskForHW3/Program.cs
> +                switch(choise.ToLower())
I wanted to use “exit” instead of “4” but forgot to remove “ToLower” later, corrected

2021-02-12 08:43 UTC, radzevich approved these changes

2021-02-12 17:15 UTC, merged